# Generated by Django 6.0.4 on 2026-04-09 05:45

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_socialmedia_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(storage=app.models.get_raw_storage, upload_to='resumes/'),
        ),
    ]
